### PR TITLE
API changes and cleanup for 1.0 release

### PR DESCRIPTION
**Pull request by lukasf**
This PR does the API changes and cleanup for FFmpegInteropX v1.0 that we discussed about in #226.

- Remove deprecated APIs
- Rename main class to FFmpegMediaSource
- Adjust namespaces to FFmpegInteropX
- Reorganize repo files
- Add FormatInfo to solve #164

### CODE REVIEW

**Review by brabebhin — APPROVED** [review]
Looks good!

**Comment by brabebhin** [comment]
Should we add support for winUI 3 desktop for C++/winRT?

Installing this package seems to be causing compiler errors (it seems to require direct reference of both the ffmpeginteropx.winmd and win2D winmd).

**Comment by brabebhin** [comment]
I fixed the merge conflicts.
This should be ready for merge.

**Comment by brabebhin** [comment]
I pushed the breaking changes from the C++/WINRT migration. These are the metadata API returning MapView<string, IVectorView<string>> and removing the delegate for codec required event args, and used the built-in winRT EventHandler delegate. This last change is also very minor.

**Comment by lukasf** [comment]
Thank you, looks good

**Pull request merged**
