### PR TITLE
Video filters

### PR DESCRIPTION
**Pull request by mcosmin222**

### CODE REVIEW

**Comment by mcosmin222** [comment]
I will create the config class + helper method.

**Comment by mcosmin222** [comment]
While this works very fine in the sample, I get the following error in my own app

Unhandled exception at 0x00007FF85B913372 (Microsoft.Graphics.Canvas.dll) in 0xC0000005: Access violation reading location 0x0000000000000001.


 	Microsoft.Graphics.Canvas.dll!00007ff85b913372()	Unknown
 	Microsoft.Graphics.Canvas.dll!00007ff85b991bdb()	Unknown
 	Microsoft.Graphics.Canvas.dll!00007ff85b98db68()	Unknown
 	Microsoft.Graphics.Canvas.dll!00007ff85b991c56()	Unknown
 	Microsoft.Graphics.Canvas.dll!00007ff85b98daa2()	Unknown
 	Microsoft.Graphics.Canvas.dll!00007ff85b98da49()	Unknown
 	FFmpegInterop.dll!Microsoft::Graphics::Canvas::ICanvasDrawingSession::Antialiasing::set(Microsoft::Graphics::Canvas::CanvasAntialiasing __param0)	C++
>	FFmpegInterop.dll!FFmpegInterop::BasicVideoEffect::[Windows::Media::Effects::IBasicVideoEffect]::ProcessFrame(Windows::Media::Effects::ProcessVideoFrameContext ^ context) Line 110	C++

**Comment by mcosmin222** [comment]
Ok, that seems to have been an UWP target version mismatch. My app was targeting 14XXX-17763 and the ffmpegInterop project was 10240-15063. Not sure why this is happening, but we need to up the target version between 10240-17763.

We can then use the latest nuget package, which seems to work well. I tested with both my app (which targets 17XXX) and sample app (which targets 15063) and the filter works fine.

As long as we implement the proper guards for APIs, there should be no problem with upping the SDK version.

**Comment by mcosmin222** [comment]
And there's another problem that needs figuring out: When the source is a MediaPlaybackList, video playback freezes after the 1st item is done.

**Comment by mcosmin222** [comment]
Ok, so after some investigation, here's what I found...

The thing does not seem to be thread safe, so I'd say we should protect the global state with mutex.
The issue has something to do with the canvasDevice. 

The difference between a MediaPlaybackItem and a MediaPlaybackList as source seems to be that the Close and SetEncodingProperties methods are called several times before playback even starts.

**Comment by mcosmin222** [comment]
The problem seems to be

A valid type has not been set for this stream or a stream that it depends on. (Exception from HRESULT: 0xC00D6D60)

**Comment by lukasf** [comment]
I have a feeling that this might be more a problem of making the effect mandatory.

Can you try setting "true" as second parameter in the AddVideoEffect method? This will make the effect optional, so playback succeeds even when the effect cannot be added to the pipeline. It might be that there is only a temporary situation where the effect must be disabled, while MF switches to next file. Hopefully, the effect will be re-enabled as soon as the next file is playing.

When opening multiple files in the sample app, I also see multiple calls to SetEncodingProperties and other methods on the effect instance. This does not seem to cause any problems.

**Comment by mcosmin222** [comment]
Yes. Setting the 2nd param to true allows me to play more than 1 item in the list. With it to false it freezes after the 1st. But then the playback list will skip some items at random.

I did notice that adding a new item in the list causes a close/set encoding properties. Probably MF recreates the pipeline or something. My guess is that removing one also does that - i remove old items after they have been played. I will try to not remove them and see what happens. I also applied the dispatcher timer treatment to adding items in the list and this greatly reduced the number of skipped items. Perhaps it is something related to marshalling operations. I will dig some more in the coming days.

**Comment by mcosmin222** [comment]
Sadly, no difference. I am somewhat out of ideas ^^.
Guess we could merge this anyway, but we cannot use this with our lazy loaded media playback list....

**Comment by mcosmin222** [comment]
Here's a crazy one. It is so crazy i won't even ask you to try it. But I will.

I think this can be fixed with a custom rendering surface. Did some digging, you can apply win2D effects to a Compositor. This should technically be on the "other side" of the rendering pipeline and not depend on the media source, but rather on the playback surface. If this works, it could prove to be an alternative to what we already have. But this would be totally independent of what is done in this branch. 

If I am successful, I will push the composition surface framework and then maybe we could add some future functions as well. I just hope i don't have to render subtitles manually.

**Comment by lukasf** [comment]
It will be interesting to see how that works! :D

Thinking about this, there is one more way to realize this: Use Win2D in XAML as backdrop brush, placed above the video to alter its colors. This would allow using the normal Media(Player)Element without custom rendering.

The Windows Community Toolkit does something like this:

https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp.UI/Media/BackdropInvertBrush.cs

It should also work above video controls. You'd only have to be careful to place the brush above the video layer but below any MediaTransportControls, to not alter your button appearance.

For both variants, we'd have to see how the performance is. As I understand, there are some optimizations done to improve the performance for video playback, when the video is fullscreen and no controls are placed above it. The brush approach might break these optimizations, and for custom surface rendering I don't know.

**Comment by mcosmin222** [comment]
Hmm that sounds easier to realize than a custom rendering surface, might try this one first. I see it is plug & play in xaml, we would only need to modify the style of media(player)element and attach it directly to its rendering surface.

Nice find!

**Comment by mcosmin222** [comment]
So I tested with xaml composition brush thingy, seems the Color Matrix effect does not seem to work. So I guess dead end.

**Comment by mcosmin222** [comment]
I also tested the custom composition surface. It does not display subtitles, so right out it is useless.
However, neither can you apply the effect. It requires a SpriteVisual to draw the video frames, and the sprite visual only accepts the brush coming from the composition surface, so it is not possible to mix it with other brushes.
Even so, after some more testing this morning, the problem continues to manifest itself even in release mode, although much less frequently. At this point I think we can outright assume we cannot use IBasicVideoEffect with MediaPlaybackList.

I also did some digging on how this seamless playlists work in MF. Apparently, there should be at most 2 topologies loaded in memory at any given time: the one in playback and the next one. However, the playback session can decide to load as many topologies in memory as it pleases. This explains why adding an item to the media playback list reattaches the effect: it must create the new topology, AND adjust the stream of the current topology so it can do seamless playback with the next.

What I don't understand is why this effect doesn't join the MF pipeline much latter in the process. It seems counter intuitive to realloc the effect each time a media playback item is created, when it could be much closer to the render output and intercept the media stream after each playback item has been abstracted away. 

I think we will need to either find a way to make the effect join later in the pipeline (I don't know if that's even possible) or come up with some other form of gapless playback.

Generally speaking, provided we do the nuget update and bump the version numbers, this PR could be merged. There is no problem with the effect itself, but rather how it is consumed.

**Comment by mcosmin222** [comment]
Anyway, back to it @lukasf 
is it ok to bump the version numbers for the projects and the nuget?

**Comment by lukasf** [comment]
I am fine with upping the target versions (although I did not really understand why it is needed).

**Comment by mcosmin222** [comment]
This is because the nuget on 1.18 version is bugged and doesn't work properly with apps that have minimum version of anniversary update.
The push fixes the issue.

**Comment by mcosmin222** [comment]
Sometimes one really has that urge to scratch, so I scratched.
I created an empty IBasicVideoEffect, and attached it to a preloaded MediaPlaybackList (no incremental loading), all done according to the book.
And guess what...

It STILL fails to open some items. At this point I am pretty sure this is a bug. Unless there is some really weird threading thing like the one with subtitles.

**Comment by lukasf** [comment]
Did you try with memory type CpuAndGpu? In my implementation I only allow Gpu. Originally I wanted to support both, but I could not get MF to use Cpu path at all. Even if I set memory type to Cpu only and force software decode, the effect would refuse to load, it would only load as Gpu. So I set to Gpu only and removed all Cpu code.

**Comment by mcosmin222** [comment]
Same result, unfortunately.
The worst part about this is that it probably will never get fixed. Media guys at MS aren't exactly chatty or cooperative. I wonder what we will have to do to get our hands on the sacred codex of MF documentation. 

As a side note, for me it loads the effect just fine when I set CpuAndGpu (or whatever it is called). The processing of frames is rather different, and didn't bother with it. I just made it read only and allowed frames to just pass through, with no processing. And the error still occurs. And I also think MF prefers CPU decode over GPU one (not sure why).

I can create a sample app for you to try if you want. I will have to create one for Microsoft anyway. And this is happening without even using our media stream source, I just create MediaPlaybackItems from StorageFiles. 

So unless we create our own media playback list, I do not see how we can fix this. I am almost ready to let it go and just deal with the fact that gapless playback + video effects is simply not possible.

**Comment by mcosmin222** [comment]
I think i might have missed something in the xaml effect attempt. I will give it another try.

**Comment by mcosmin222** [comment]
Anyway, this is the sample

https://1drv.ms/u/s!Ao-WOwsImxSMt502DdQeWGdSBMOyqw

I just re-entered the insider builds program, just to see if this gets any better in future versions.

**Comment by mcosmin222** [comment]
Looks like the forum mods managed to reproduce the bug and will report it to media team. So there's hope 😇

**Comment by lukasf** [comment]
You mean the MediaPlaybackList + video effect bug? Would be really cool if they manage to fix it.

**Comment by mcosmin222** [comment]
Yes. That's the bug i've been trying to go around with all the spam lately.

Anyway, that being said, I think it is time to merge this. Unless you want to wait it out until they fix it.

**Comment by lukasf** [comment]
I don't intend to wait for a fix. But I think the API is a bit bloated right now. Three classes were added for just one video effect, and I think it could instead all be done with one simple class (I already have somting in mind here). Additionally, I want to add parameter restrictions, because the effects (except matrix) will throw exceptions during processing when values are out of range. I might have more time again this weekend or next week to work on this.

Can you add an entry on WPDev UserVoice to either automatically include subtitles in MediaPlayerSurface, or to add a RenderSubtitlesToSurface which accepts a CompositionSurface (or some other concept to get subtitles into composition space)? Maybe they are not even aware of this gap.

You asked about adding native ffmpeg HW acceleration. D3D11 is supported since quite some time by ffmpeg, I investigated this a year back. One thing I then requested on UserVoice is the creation of samples form D3D surface, to theoretically allow hardware acceleration. This was actually added to the Windows API, now it should be possible to pass GPU samples down. So yes, theoretically we could build our own ffmpeg hardware acceleration, which would be cool (and open new possibilities such as adding HW video processor effects). The main problem is that the ffmpeg lib only contains very few basic functionalitites for this. The majority of code would need to be provided by us (such as maintaining a buffer pool, allocating buffers, creating and configuring the D3D video device, feed samples to video device, handle device reset). A basic implementation of DXVA2 can be seen in the ffplay (D3D11 will be roughly similar). Also MPC and other players have implemented those interfaces, this could be used for reference. But it really is a lot of work unfortunately, so while it would be cool, I am not very enthusiastic to go that route right now.

**Comment by mcosmin222** [comment]
I see. Thanks for the info.
I have been investigating the possibility of having a custom rendering surface and I think it might be possible to do it without involving ffmpeg hardware acceleration.

In theory we can use a SwapChainPanel with directx interop and MediaPlayer in video frame mode, and render frames drom MF onto the custom rendering surface. I think we can apply shader to it and obtain hardware acceleration. 

I intended to try it out for this effect problem, but since media team reproduced the bug, I stopped trying.

**Comment by lukasf** [comment]
I have removed MediaPlayerHelpers. Now we just create an instance of the config class and call AddVideoEffect() right on that instance. This is a bit simpler to use IMO.

I think we still need parameter checking: When out-of-bounds values are used for Win2D effects, exceptions are thrown during rendering. I think we should throw as well, when invalid values are assigned. We could think about moving all color matrix values to a default 0, range -1 to 1. Then all values except sharpness have same range and default, that would make building UIs for it easier.

**Comment by lukasf** [comment]
So, I now normalized all ranges (except sharpness) to -1 to 1. I also added a video effects section to sample apps, so we can play with the settings.

What do you think of the latest version?

**Comment by mcosmin222** [comment]
I hooked it up to my app, and disabled the checks. 
Contrast can go lower than -1.

i.e this is for -2:
image

Saturation can also go to -2.
image


brightness -> +/- 2  Some files are visible at less than -1 brightness
this is -1.24
image

The bounds I set through trial and error:

Brightness: -2/+2.
Ccntrast: -2/+2
Saturation: -2/+2
Sharpness: 0/+2
Temperature: -1/2
Tint: -2/2

Note that within these bounds, the effect is usually stable. The only one I am not sure of is tint.

**Comment by mcosmin222** [comment]
I hooked up my app to it and disabled the checks.

Contrast is 2 here:
image

image

we can also go lower:
image

image

Or we can obtain some more weird effects:

image
image

I think only temperature and tint are bound to the -1/1 interval.
If I put tint to lower than -1, it will not crash, but the video will not move to the next frame either.

**Comment by lukasf** [comment]
Temperature, Tint and Sharpness are Win2D effects, they will throw exceptions during process call when wrong values are used. I catch those exceptions, so the app will not crash, but there won't be any output. I think it would be best to throw early when setting those values in our config class.

The other three parameters are used in my custom matrix effect. Indeed they are not really limited, we could remove the checks if you like, for artistic purposes :).

**Comment by mcosmin222** [comment]
Yes. I think this is for the best. Throw exceptions when needed, otherwise not limit the API. :)

**Comment by mcosmin222** [comment]
Another thing crossed my mind: how would the frame grabber work with the video effects? Right now it would grab the frame before effects are applied.

Should we worry about this? I guess we could add a flag to capture the next frame in the video config and save the frame to disk.

**Comment by lukasf** [comment]
We don't have a reference back to the config from the video processor, and the config could be used for many instances. If this is really required, I'd rather see a config parameter in the FrameGrabber, and then we'd have to implement a method to do the effect processing manually on the FrameGrabber output image (create processor inside frame grabber and call that method).

**Comment by mcosmin222** [comment]
I might do it some day.

the last commits look fine. I will do some tests later today.

**Comment by mcosmin222** [comment]
All good.

**Comment by lukasf** [comment]
Meged

**Comment by mcosmin222** [comment]
I checked the status of the IBasicVideoEffect & MediaPlaybackList and it seems to have gotten far worse in the meantime. It barely gets to play 1 file out of 4-5. 

Although this time it is a different error: 

WinRT originate error - 0x8000000B : 'The operation attempted to access data outside the valid range'.

**Comment by lukasf** [comment]
Oh man. Maybe this should be reported to Microsoft? BasicVideoEffect does not depend on anything in our lib, so it should not be too difficult to create a repro that shows the bug.

Do you modify the MediaPlaybackList on the UI thread?

**Comment by mcosmin222** [comment]
I reported it back in may, and i have been following the news...

I do create the media playback list on UI thread but I think the modification happens on background. This is actually worth checking out.

**Comment by mcosmin222** [comment]
So I tried that, creating, adding and removing items in Dispatcher callback, but didn't help.
I think my laptop is also somewhat bugged, because I entered the insider program sometime in june, and then I didn't receive any update in the meantime (I just realized this today!), and not I am trying to fix this and get a more recent build.

**Comment by mcosmin222** [comment]
Still not fixed in 1909....

**Pull request merged**
