### PR TITLE
Pass channel layout to MF engine

### PR DESCRIPTION
**Pull request by lukasf**

### CODE REVIEW

**Comment by mcosmin222** [comment]
oops, I think I found a bug. Let me see if this is related.

**Comment by lukasf** [comment]
I added one more commit to select the preferred 5.1 default layout and not use the broken ffmpeg default for 6 channels.

I had raised an issue about wrong default on ffmpeg change tracker, but it was closed. They said it might be incorrect behavior, but changing it could break a lot of apps, so they are gonna keep it. The default is directly related to command line interface, so changing it would change some parameter meanings on cli as well...

**Comment by mcosmin222** [comment]
Ouch. I guess this is the best we can do.

**Comment by lukasf** [comment]
Merged...

**Pull request merged**
