### PR TITLE
expose avformatctx metadata

### PR DESCRIPTION
**Pull request by mcosmin222**
First commit PR for #105

### CODE REVIEW

**Comment by lukasf** [comment]
Looks good so far!

Two proposals:
1. Expose as IMap<string,string> instead of custom type.
2. Delay-initialize, so the map is only created on first access of that property on MSS

**Comment by mcosmin222** [comment]
1. I will have to test what happens if there are 2 tags with same key (I know it is not standard but might happen on broken files). This is the reason I did not expose it as IMap (yet).
2. Sounds good.

**Comment by mcosmin222** [comment]
So, I delayed the initialization.

As for IMap. I still don't feel like we should push this towards making it a dictionary (in case broken files have duplicate tags, apparently this is not that uncommon).

So my suggestions would be...

Have a Map of <string, Vector<string>> to deal with duplicates.

Implement our own IKeyValuePair class (which we might need in the future anyway - apparently winRT does not expose its own), and return it as a Vector<IKeyValuePair>, which would basically be very similar to what we have now, except the custom store class will be projected in C# as KeyValuePair object.

Honestly I'd prefer the first approach. What do you think?

**Comment by lukasf** [comment]
Are you sure that we can hit duplicate entries? You are reading the values from an AVDictionary. According to docs, it is not even possible to add duplicate entries to an AVDictionary (any second call to av_dict_set with same key would overwrite the previous entry). So I would assume that we cannot ever get duplicate entries from that interface. And then I think we should go for IMap (or better, IMapView), because it is the best and most convenient way to expose unique key/value pairs.

If a file would contain multiple entries with the same key (which is of course possible), then I am pretty sure FFmpeg will only return one instance of that entry. I already mentioned that if you want a full blown tag reader, you should rather look into a dedicated library for that. Then you can also enumerate different kinds of tags (ID3, ID3v2, Vorbis, APE) which might even co-exist in the same file. But FFmpeg only has basic support for this (which should be enough for most needs).

**Comment by mcosmin222** [comment]
I created a public class to expose an implementation of IKeyValuePair<string, string>. Sadly, C++/CX cannot export generic classes as it seems.

**Comment by lukasf** [comment]
What would you think about moving the vector down directly to the MSS class, to save the indirection through MediaMetadata class? Or do you plan to add other properties to MediaMetadata?

**Comment by mcosmin222** [comment]
hi @lukasf 
At first I thought I could add other properties, like the timestamp at which the metadata arrived (i.e in case of live streaming). Then I realized this was not easily done, because the metadata is exposed in AvStream, but the class remained anyway.

I don't think there is any harm done in keeping it this way. We might have other ideas in the future, and as you pointed out, the Mss class is rather huge anyway and it is becoming unwieldy, so best to minimize impact on it as much as possible.

**Comment by lukasf** [comment]
There are some things that could logically fit in, like attached files or thumbnails. But the downside is that we could not lazy-initialize those separately, because we cannot keep a reference back to the MSS or AVFormatCtx. We'd have to initialize all contained metadata on first access. So if someone only wants to read tags, we'd have to load covers and all attached files (e.g. subtitle fonts) as well. Maybe it's not a big problem, but efficiency would be best if we'd only init what is actually requested, and that would lead us to separate properties directly on the MSS.

We could keep the MediaMetadata class internally, but not expose it. That way, we would keep the implementation out of the MSS class, but still have the benefits of fine-grained delay-initialization of all areas.

I think the API surface on the MSS class is ok, it's just that there is too much code inside. I had thought about introducing some kind of "StreamBuilder" class, which would do the whole stream parsing and creation of sample providers. That would help a lot to bring the MSS code size down.

**Pull request merged**
