### PR TITLE
Add FFmpeg 4.4, openssl and AV1 SW decoder

### PR DESCRIPTION
**Pull request by lukasf**
I failed to cleanly separate my activities, so this is a combined pull request.

The following changes have been done:
- Update to FFmpeg 4.4.1
- Add dav1d for AV1 SW decoding
- Add openssl 3.0.1
- Allow parallel builds of all platforms
- Capture log files of all builds
- Add a script that installs and configures all build dependencies, including MSYS2, Perl, NASM
- Add dockerfile for building inside container

### CODE REVIEW

**Comment by brabebhin** [comment]
Wow, nice job,  seems you've been busy.  I will give it a run this week.

**Comment by brabebhin** [comment]
I tried building ffmpeg, and it automatically downloaded pearl (cool). But the build failed, and it seems to have failed for all platforms. Does the parallel build undo all the changes for all platforms if one fails?

**Comment by lukasf** [comment]
You need to enable parallel build using -AllowParallelBuilds. But it is not yet working with openssl. Will push a new changeset soon to resolve all issues and add workaround for openssl x86 build.

**Comment by lukasf** [comment]
Build should work with latest changeset. Still facing this bug on my OS where the ffmpeg build hangs for x86. Working on docker approach to get reliable builds.

**Comment by lukasf** [comment]
Oh man I don't believe it. This goddamn ffmpeg x86 link.exe bug even occurs inside my brand new docker container!! How the hell is that possible? It is a clean container based on an MS image, all build dependencies are downloaded and installed from the web, it cannot access files outside the container, I am building our master branch without any of the latest changes. And every ffmpeg build hangs on linking x86 avcodec dll. This is absolutely weird. I cannot understand how that is even possible...

**Comment by brabebhin** [comment]
For me it outright fails. Maybe this can help:

"D:\Git\FFmpegInteropX\Tools\perl\perl\bin\perl.exe" ..\..\..\..\..\Libs\openssl\util\mkdef.pl --version 3.0.0 --ordinals ..\..\..\..\..\Libs\openssl\util\libcrypto.num --name libcrypto --OS windows > libcrypto.def
	"D:\Git\FFmpegInteropX\Tools\perl\perl\bin\perl.exe" "-I." -Mconfigdata "..\..\..\..\..\Libs\openssl\util\dofile.pl" "-omakefile" "..\..\..\..\..\Libs\openssl\providers\common\include\prov\der_digests.h.in" > providers\common\include\prov\der_digests.h
PS>TerminatingError(): "nmake  exited with code 2.
Original command line:
nmake "
PS>TerminatingError(): "nmake  exited with code 2.
Original command line:
nmake "
WARNING: Error occured: nmake  exited with code 2.
Original command line:
nmake

**Comment by lukasf** [comment]
Can you try without parallel build? I found that sometimes the last error message is lost when using parallel.

**Comment by brabebhin** [comment]
[Build_20210928_110443_x86.log](https://github.com/ffmpeginteropx/FFmpegInteropX/files/7245589/Build_20210928_110443_x86.log)
Here's the log file. That was without parallel builds.

**Comment by brabebhin** [comment]
I will try your changes later today. But i think x86 is a goner and it is unlikely they will fix it. Maybe we should drop support too, I doubt there are that many people running x86 OS. And many of the modern video codecs are not running well on x86 anyway.

**Comment by lukasf** [comment]
The error comes from perl code trying to generate headers. Do you have some other version of perl installed on your PC? Maybe I need to put my tools to beginning of PATH, otherwise a different, unsupported version of perl might be used accidentially.

It's strange that Start-DevShell does not do anything. Do you get an error message? Can you try to run it with -InProcess parameter?

About dropping x86, I don't know. I think it would cause lots of questions. I am pretty sure that still almost every Store App comes as both x86 and x64 (plus ARM64). People won't like giving up x86 just because of a lib. Gamers on Steam are usually more at the high end of hardware. The x86 percentage for the average user is probably a bit higher. I would not have an issue with dropping ARM, it's really 100% dead. But dropping x86, I don't think I am ready for that ^^

**Comment by brabebhin** [comment]
Well yes, I also do have pearl in the msys64 folder on C drive. This is a leftover from the old toolchain. I will try moving it and see if it works better.

**Comment by brabebhin** [comment]
This could take as long as next week, so if you have any other ideas, I'm all for trying it out.

**Comment by lukasf** [comment]
I built on different machines without openssl issues. Sure you don't have some other perl installation? Try `where perl.exe` to check.

If you have docker, you can as well try the new dockerfile. That's probably a lot easier than setting up a new VM.

**Comment by brabebhin** [comment]
The vm is almost ready. Took me a while to understand why hyperv won't boot the 32 bit iso,  but all is good now.  I will setup the dev environment and try again.

**Comment by brabebhin** [comment]
Well, it seems our build scripts will not work on an x86 machine. This is probably because the msys we install is a 64 bit executable, not a 32 bit one.

**Comment by brabebhin** [comment]
Well, Perl seems to be quite sought-after. 

image

**Comment by lukasf** [comment]
That looks a bit problematic :-D

**Comment by brabebhin** [comment]
Yeah. Matlab seems to have an older version, i need to see if i can update it...

**Comment by lukasf** [comment]
It's not just the version. You need the right edition, every one has it's own features and included libs. You should try to put our perl version to beginning of path, then it should work. Am 03.10.2021 16:32 schrieb moonshadow ***@***.***>:
Yeah. Matlab seems to have an older version, i need to see if i can update it...

**Comment by lukasf** [comment]
Try to replace this line:

`$env:Path += ";$SolutionDir\Tools\perl\perl\bin;C$SolutionDir\Tools\perl\c\bin;$SolutionDir\Tools\nasm"`

With this:

`$env:Path = "$SolutionDir\Tools\perl\perl\bin;C$SolutionDir\Tools\perl\c\bin;$SolutionDir\Tools\nasm;" + $env:Path`

**Comment by brabebhin** [comment]
Nope, still not working. I even tried a brand new dev VM in hyper V on x64 and perl isn't downloading. WTF o.O

What is the exact version of perl that we need?

**Comment by brabebhin** [comment]
I created s fresh environment on another machine and that seems to have done the trick. It is now compiling dav1d

**Comment by brabebhin** [comment]
Right, so the x86 build seems stuck on creating avcodec. Is this the bug you encounter?

**Comment by brabebhin** [comment]
Right, so x64 and arm64 build. but x86 fails?

Are we now on the same level?

**Comment by lukasf** [comment]
Yeah ok. So unfortunately, we are on the same level. I had some hopes that on your existing build system, x86 would work. But on that system, openssl does not build, if I understand correctly. Too bad.

I just remembered that I have an old laptop that might still have a build environment. I will check this week to see if that one can still build x86. And I will also report the link error. I had a few cases where bugs in the build system could be worked around by adding some additional build parameters (e.g. to disable certain compiler optimizations). At least, it's worth a try.

**Comment by brabebhin** [comment]
Ahhh I think I'm onto something.
I managed to build the master branch (I wasn't able to do it before), by changing the optimization flags.

I added

-e CPPFLAGS=-Oy

to all MAKE calls in the powershell script.

**Comment by lukasf** [comment]
Oh lol yes that is what I observed on my two machines as well. When the bug occurs once, it suddenly affects any build, even of older configurations that were working just before. Deleting intermediate files did not help, only system restore brought me back to green status (until the restore points got lost).

Interesting find though about that compiler flag. Can you tell me where exactly you added it? The make calls at the end of FFmpegConfig.sh?

**Comment by brabebhin** [comment]
There has to be something cached somewhere. Maybe in temp files or registry or something that gets affected by system restore.

I pushed the change-set with compiler flag experiments. But again, this only worked once, the 2nd time it got stuck at linking. 
For me, it only fails on x86 build. I can build x64 and ARM64 just fine (ARM seems to fail very early on, probably due to some missing VS features - the platform is dead anyway, so I didn't bother investigate it). But I need to explicitly provide the target platform. so build-ffmpeg x64 works. But build-ffmpeg x86 doesn't.

This is from the machine that built master earlier today and has many perl version
Just so I can keep it here to ensure I am not losing (or lost already) my mind...

image

**Comment by brabebhin** [comment]
Another idea we may want to try is to build using VS2022.

**Comment by lukasf** [comment]
I tried on Windows 11 with VS2022 and 14.3 compilers. Same story. The new OS looks nice, by the way. I can recommend taking a look. I installed it on a bootable VHDX file, my new preferred way for test environments. No messing with partitions and stuff, you just need some space for a dynamically growing VHDX file.

The calls you modified in your last changeset only affect Desktop/Win32 builds. They are not used at all on UWP. I think the reason why compilation worked is because you switched from ffmpeg-4.4 to master branch. Before, you ran into openssl x86 issues (these are unrelated to ffmpeg x86 link issues). On master there is no openssl, so build worked there. Similar to what I had on my PCs, once the bug occurs, it will occur on any ffmpeg x86 build you try. I am also pretty sure that it somehow has to do with caching. But deleting intermediate files does not help. And the strange thing is that the bug also occurs on any new installation, even when using older build tools. So it is not that the caching makes the bug occur. It seems more like something cached on older build systems prevents the bug from occuring, when on a fresh installation with same tools, the bug occurs right away. Very weird stuff.

**Comment by brabebhin** [comment]
I don't remember exactly how this works, can we have a newer windows SDK on an older Windows version? Or is it only older SDKs on newer windows?
I see it is possible to bring back older windows versions with HyperV.
I

**Comment by lukasf** [comment]
Sounds promising! On my existing PCs I think the bug started to occur when I included dav1d into the build. But on all new installations, it occured right away even on master branch without dav1d. So this is indeed some progress. Maybe you should create a backup of your VM, so you can go back in case the bug starts to occur.

I can only recommend using VHDX boot approach for such things in future. No virtualization involved, native performance for CPU and GPU. Only very small performance impact on disk IO, but you can access source folders on your "real" partitions, then all the IO involved during build is not affected at all. There are powershell scripts for creating a VHDX from an ISO file, only few more commands needed to add them to boot menu, it really only takes a few minutes to setup a new machine. I can give you some hints if you like. I am also working on a script that fully automates the whole thing.

**Comment by brabebhin** [comment]
Meh, it turns out even settings up a 32bit OS on a relatively new hardware (6 years old) is very difficult.

**Comment by brabebhin** [comment]
But that didn't install a meson.exe, only some weird meson (no extension) file. Maybe this is why you installed the mingw version?

**Comment by brabebhin** [comment]
I will put together the script that bypasses dav1d in the coming days

**Comment by brabebhin** [comment]
Also got w11 updated, sadly still no joy.

Speaking of w11, i feel like the taskbar is a complete regression, hopefully they will bring functionality on par with 10.

**Comment by brabebhin** [comment]
Hello @lukasf 

I have been playing some more with this branch. The current head will not work for me, regardless of what magics I try. The weird thing is, if I hardcode 

> --disable-libdav1d  \

in ffmpegConfig.sh, it seems to do just fine with x86. But if I use the current "smart" approach, there seems to be no difference.
Even something like this makes it get stuck

> configureArgs="\
>     --toolchain=msvc \
>     --disable-doc \
>     --arch=${arch[$platform]} \
>     --enable-${sharedOrStatic} \
>     --enable-cross-compile \
>     --enable-debug \
>     --enable-zlib \
>     --enable-bzlib \
>     --enable-lzma \
>     --enable-libxml2 \
>     --enable-iconv \    
>     --enable-openssl \
>     --target-os=win32 \
>     --pkg-config=$DIR/Intermediate/pkg-config.exe \
>     --prefix=$outDir \
> "
> 
> if [ "$platform" == "x86" ]; then
> configureArgs="\
>         $configureArgs \
>         --disable-libdav1d  \
>         "
> else
> configureArgs="\
>         $configureArgs \
>         --enable-libdav1d  \
> 		"
> fi

I am so out of ideas :(

**Comment by brabebhin** [comment]
Hello again @lukasf 

current mood:
OMG I think I did it!!!!

So here's the crazy story:

Remember when I created the 32 bit VM but couldn't build dav1d because there is no 32 bit meson ninja thingy? Well, I realized that since the problem isn't building dav1d but linking it into FFMPEG, I could build dav1d on one machine (64 bit) and then copy it to the intermediate directory of the 32 bit VM, and then proceed to build ffmpeg as if nothing happened.

And it seems it worked...
The linker doesn't get blocked anymore on the 32 bit machine.

here's the log file.
I will now need to try out the new binaries...

[Build_20211213_152245_x86.log](https://github.com/ffmpeginteropx/FFmpegInteropX/files/7704323/Build_20211213_152245_x86.log)
.

**Comment by brabebhin** [comment]
aaaand it works.

Basically how I feel right now...

image

**Comment by brabebhin** [comment]
Ok, now that the euphoria is over, there's still the problem of automating the build. I don't think my manual hack is a long term solution. But at least we know what the problem is...

**Comment by lukasf** [comment]
Wow nice work @brabebhin!!

I would not have expected this to work, i mean, linking a lib that was built by a different compiler. But you proved different. Unfortunately, as you say, it is not really possible to turn this into an automated build. Also, it requires to switch a PC from UEFI to legacy boot with slower boot times, which I do not want really to do with my machines.

**Comment by brabebhin** [comment]
Welcome back @lukasf 

I do have some older hardware sitting around., doing nothing. If you have some plan on how to do it, I could give it a try on that.

**Comment by brabebhin** [comment]
Hello again @lukasf ,

As far as I can tell, x86 builds work on x64 machines as long as msys32 is used (instead of msys64).
So basically, the x86 build would go like this:
1. Build dav1d with x64 msys64.
2. Do the rest of the build with msys32.

I could upload the msys32 folder that I am using to onedrive, so that we can keep using it for all eternity.

What do you think of this plan?

**Comment by lukasf** [comment]
@brabebhin WOOHOO I think I just nailed this f*** thing once and for all!!

You gave me the right hint: It builds successfully when building it on a x86 system. Today it just came to me: Every x64 CPU can run x86 code. Do we even need a x86 VM? Why not use the native x86 build tools even on a x64 machine, instead of the x64_x86 cross tools?

Basically it was just adding these few lines in the Build-Platform() function

```
    # Build x86 with x86 toolchain
    if ($targetArch -eq 'x86')
    {
        $hostArch = 'x86' 
    }
```

And the build succeeded!! YAY!!

So now it looks like we have a working build system again, for all platforms without issues. It includes ffmpeg 4.4, openssl and dav1d. And I think if we build it with the latest SDK, it should even allow AV1 HW acceleration. I will try that in the next days.

Now I guess I feel like you felt when you posted that screenshot above. :-D

**Comment by brabebhin** [comment]
Wow nice work!!! I can't believe it was that simple all along.

In the beginning i always assumed it was OS specific, since you mentioned it didn't work with docker. Guess we didn't need either in the end.

Nice work!

**Comment by brabebhin** [comment]
I can confirm that x86 build. Nice work!!! 

Nightmare is over xD

**Comment by lukasf** [comment]
Good to hear that it works for you as well!

There is still something to do: Fallback to AV1 SW decoding does not work properly, and it is not trivial to fix. In ffmpeg, all other HW accelerations are built right into the native software decocder. This is different for AV1. There is one codec "libdav1d" that uses the lib for software decoding. And there is "av1" which uses HW acceleration but cannot do SW. By default, ffmpeg will prefer libdav1d. So unless we force SW decode, I try to create "av1" instead and initialize it. But it does not have a device yet at this point, so initialization will always succeed. And even during playback, we do not even get an error. Looks like the av1 codec just returns blank SW frames, if HW decoding fails. It does not even error out! Pretty strange behavior if you ask me.

Getting proper SW fallback is not trivial: We need to check the first result frame format. If it is not a HW format, we need to create and initialize our dav1d sw decoder, and replace the HW decoder with it. We must store the first packet that was fed into the HW decoder. In case of fallback, we must push the same packet into the sw decoder, and then get the decoded frame off it. This will be a pretty nasty workaround. Not very happy about that. But I do not see any alternative. I'll see if I find some time for that during holidays.

But I can confirm that in general, SW decoding as well as HW decoding of AV1 works. Performance of the SW decoder is surprisingly good. And HW decoding works on devices where GPU is capable. On others, it will currently show a blank green image, due to missing fallback.

**Comment by brabebhin** [comment]
Hi @lukasf 

Here's something you can try (unfortunately i don't have an av1 capable hardware).

Create a ID3D11Device manually. AFAIK, this should always point to the hardware device that does the decoding, even if the virtual adapter is not valid for rendering.

With that temp device,  you should be able to see if AV1 is supported. You should be able to correctly pick the right decoder.

We need to test this with dual GPU devices, like laptops with both integrated and dedicated GPUs. Especially with the scenario in which the app is opened on ome screen and moved to a screen that's connected to a different GPU.

**Comment by lukasf** [comment]
I fear that we would run into issues with multi GPU in that case. I also don't have such a setup here for testing. But we could perform the test when the GPU device is assigned. That is before first decode happens, which makes things easier.

**Comment by brabebhin** [comment]
iirc, the device on which you opened the application will always do decoding. And if you move the application to a second monitor connected to a second device, that second device will do rendering. We actually do have a check for this.

**Comment by brabebhin** [comment]
I gave it a try based on CodecChecker (we actually already do this!) checking for the D3D11_DECODER_PROFILE_AV1_VLD_* profiles from DirectX11, and it correctly says the GPU does not support it.

However, I do not an AV1 capable GPU, so I cannot know if it really works.

**Comment by brabebhin** [comment]
Hi @lukasf and happy new year!

Do you have some changesets pending? I might be able to test this, and if you don't have anything coming, i could code the changes myself.

**Comment by lukasf** [comment]
Happy new year as well @brabebhin!

I already have working code since a while. I will try to cleanup and push the changeset soon!

**Comment by lukasf** [comment]
Okay so the changeset is online now. I tested on two devices, one which has HW acceleration and one that doesn't. It should even work in multi GPU scenarios, when moving a window from an AV1 supporting GPU to a different GPU that does not support AV1. It should fallback to SW decoding dynamically, and re-enable GPU decoding when moving back. I cannot test this here though, due to lack of such a system. It is a pretty exotic scenario anyways...

I have to say again that I am really surprised by how well the SW decoding performs. When checking AV1 SW decoding last time (quite a while ago), performance was totally unacceptable. I was sure that SW decoding AV1 high-res (4K) files would be impossible for a long time. Now with dav1d it runs smooth even on my laptop, which is a few years old. GPU decoding is still king, of course.

**Comment by brabebhin** [comment]
I can confirm that software decoding detection is working now properly. I will give it a try on some working hardware as well, but since you already tested it is probably fine.

The dav1d performance is directly proportional to the nuisance it was to link it xD
Regarding the multi GPU setup, I don't have a combo that could test it, nor do I know anyone who might have, so I guess we will just need to go along with it. The only way I can see this happening is through some sort of external GPU or multi GPU desktop.

**Comment by lukasf** [comment]
I think that we are ready for merge now. Also updated readme and stuff.

@MouriNaruto Just for your information: I am removing the reference to FFmpegUniversal from the README.md. Since we moved to Nuget packages a while ago, deployment is greatly simplified, and I do not see a benefit in using FFmpegUniversal now. It also has not been updated since quite some time.

**Comment by brabebhin** [comment]
Hi @lukasf 

Sorry I tested it but then got carried away and forgot to mention it.
Yes, we're good to merge.

Thanks and nice work!

**Review by brabebhin — APPROVED** [review]

**Comment by MouriNaruto** [comment]
@lukasf 

I think it's OK to remove FFmpegUniversal branch.

Kenji Mouri

**Comment by lukasf** [comment]
Hi @MouriNaruto,

you said that you are planning to do a new implementation of FFmpegUniversal using NuGet. What is the reason for that? I understood the motivation for FFmpegUniversal, when you manually had to care abour deployment of all Fmpeg dlls. That was quite a hassle, especially because the dll names changed frequently during FFmpeg updates. But now that the deployment is fully automatic using NuGet, what is the benefit of having a merged dll vs separate dlls? As a dev, you won't notice a difference in your workflow, and for the users it should not make a difference as well. Just curious.

**Comment by MouriNaruto** [comment]
@lukasf 

> But now that the deployment is fully automatic using NuGet, what is the benefit of having a merged dll vs separate dlls?

- It can reduce at least 2MB binary size. (If we enable some third-party modules and merge them, we can reduce more space.)
- It can keep the output binary file tree tidy, I hope I can use FFmpegInteropX in my desktop application with MediaPlayerElement control via XAML Islands or Media Foundation directly. (My app will support portable mode. Based on that, I will try to rewrite this project with C++/WinRT because I can use some open source infrastructures make the binary only rely on ucrtbase.dll. I will try to provide my rewrite implementation to this project because I love creating or contributing to open source projects.)
- Use NuGet is only for simplifying the build process.

Kenji Mouri

**Comment by brabebhin** [comment]
Unfortunately, neither using MF directly nor the XAML islands is a realistic prospect, either because of complexity involved or because of performance issues. Also WindowsAppSdk currently does not support MediaPlayerElement which is quite a shame, and there is also no roadmap for it. Given Microsoft's recent track record, it may very well mean we will not get built-in media controls in Windows App SDK.

I personally tried re-creating MediaPlayerElement using win2d and directx surfaces. coupled with MediaPlayer FrameServerMode, however, I cannot get the subtitles to render. Otherwise everything works fine.

**Comment by MouriNaruto** [comment]
@brabebhin 

I don't think it's OK to use Windows App SDK at present. Because there are many missing features and the dependency binary size is really huge.

Kenji Mouri

**Pull request merged**
