### PR TITLE
Update to ffmpeg n5.1

### PR DESCRIPTION
**Pull request by lukasf**

### CODE REVIEW

**Comment by lukasf** [comment]
FFmpegInteropX.FFmpegUWP 5.1.0-pre nuget is available now for testing.

**Comment by brabebhin** [comment]
Build works fine for me too.

**Comment by brabebhin** [comment]
Any news from Microsoft?

**Review by brabebhin — APPROVED** [review]

**Comment by lukasf** [comment]
I did not yet submit the build issue to Microsoft.

I read on the FFmpeg mailing list that a 5.1.1 is planned very soon, because of an unusually high number of bugs in 5.1. So I think we should wait and directly go for 5.1.1.

Offtopic: Right now I am trying to get my DASH improvements (multithreaded substream initialization) into FFmpeg, that's why I am on the mailing list. I did the changes a year ago, then I got quite busy, and only months later I realized that I lost the changes on a OS re-installation. Now somehow I found the motivation to re-implemented this. It will be interesting to see if they like it and if it will get merged.

**Pull request merged**
