### PR TITLE
Simplify Bash script

### PR DESCRIPTION
**Pull request by JunielKatarn**
- Drops non-Win10 variants
- Centralize common configure arguments.

### CODE REVIEW

**Comment by lukasf** [comment]
Hi @JunielKatarn, have you seen PR #173? It picks up some of your optimizations, but also adds lots of other changes. I had problems with my build machine, and I did not have much time recently, so I did not work on that branch for a while. But #173 is the way forward, switching to nuget and better build scripts. I will not accept other PRs reworking build scripts, since that would lead to massive merge conflicts lateron.

**Comment by JunielKatarn** [comment]
@lukasf 

I see those changes now.
I'd like to have the SH changes sooner than later.
Perhaps I sync this PR and the #173 branch so this individual file can be submitted?

**Comment by JunielKatarn** [comment]
#201 published to update the branch instead of master.

**Comment by lukasf** [comment]
Can we close this PR?

**Pull request closed without merging**
