### PR TITLE
Add support for Visual Studio 2019

### PR DESCRIPTION
**Pull request by lukasf**
- Fix libraries to build properly with VS2019
- Make use of v142 C++ build tools with VS2019
- Update readme

### CODE REVIEW

**Comment by lukasf** [comment]
You need to run `git submodule update` after pulling the changes, to get libraries up-to-date.

**Comment by mcosmin222** [comment]
Cool. I will install VS and give it a try in the evening or tomorrow.

**Comment by mcosmin222** [comment]
I suppose this test cannot be done with side by side installs of VS2017 and VS2019, correct?

**Comment by lukasf** [comment]
Our build script will select VS Latest, so you can test this with both installed. I have uninstalled VS2017 and it still builds for me.

**Comment by mcosmin222** [comment]
So, I have both installed and worked fine.
Guess this covers all cases?

**Comment by villagra** [comment]
I can confirm everything works fine now. 👍. Thx

**Pull request merged**
