### PR TITLE
Implement fast seeking to solve #184

### PR DESCRIPTION
**Pull request by lukasf**
This will allow to use fast (keyframe) seeking.

Basically it works even without the second seek, for both compressed and uncompressed streams. But I noticed that there is sometimes a small audio distortion after seeking. This is because audio packets are usually encoded a few ms before corresponding video frames (audio preroll). So there is a small gap without correct audio when we start playing right at the keyframe position, which MF seems to fill with a small repeat audio that sometimes glitches.

I introduced a second seek to compensate for audio preroll, then drop all packets in both streams until they are at the keyframe position. Then we have the exact right packet to start with in the queue for both streams, allowing 100% glitch free playback from keyframe position.

I am not exactly sure where to put the config option. Shall we have it on the MSS (as I implemented now) or in the config class? Or have it in both (like for BufferTime: default value in config class, plus override in MSS instance)? Also, should we make the second seek optional? The additional delay is barely noticeable for local files I tried. It could make a difference when files come from a slow source.

### CODE REVIEW

**Comment by lukasf** [comment]
@sudongg Let me know if this works for you as expected.

**Comment by lukasf** [comment]
Added config options. I have currently enabled FastSeek by default. It seems to work very well for the files I tried. However, it could give bad seek precision for very short files with large keyframe intervals. So I am not 100% sure if it should be enabled by default (this could be considered a breaking change).

**Comment by mcosmin222** [comment]
I suppose there is no way of using fast/slow seek automatically? 

Could we detect a delta between the desired seek position and the key frame, and if the delta is above a certain threshold, use the show seek? But this would essentially mean seeking twice...

**Comment by lukasf** [comment]
I have thought about that as well. It would not require a second seek: Slow seek is essentially the same as fast seek. It also goes back to the last video keyframe. The only difference is that we do not report the actual position. Then MF/UWP will decode frames from the keyframe up to the desired seek position, before starting playback. Only fast seek with clean audio has a second seek, but we can do the delta checking before that second seek and just skip it if we do slow seek.

But auto switching to slow seek based on delta has a strange effect: It will switch to slow seek exactly in those cases where fast seek would have the most effect.

If we add a delta check, we could do this as a relative value. So seek precision must be a certain percentage (e.g. 0.5%) of the total duration of a file. Then for large files, we will almost always have fast seeking, for smaller files we might fall back to slow seek (depending on keyframe interval) and for very small files, we will almost always have slow seek (which is still as fast as it is now).

Still I am not sure if this is really such a good approach. The alternative would be just adding an explicit function in the app, e.g. press shift during seek to have precise seek.

**Comment by lukasf** [comment]
Even with auto switching, it would still be a breaking change for such apps, at least for smaller files. The only way to avoid this is to disable FastSeek by default. I think we should just do that. It's a cool feature, but devs should decide if/when to use it.

**Comment by lukasf** [comment]
I have noticed that for some files, when I have FastSeek enabled, pressing my "skip forward" arrow key might even send me back to a previous position. That's of course unexpected and undesirable I'd say' it's even worse than just having bad accuracy on a seek bar (the other scenario we had above). Still I'd like to keep FastSeek enabled even for arrow navigation, because it really helps stepping quickly through slow files. Luckily, for that scenario it should be possible to add a good auto correction. Just perform a second seek without "backward" seek flag, if we find out we accidentially landed before playback position. I will try to get this working somehow.

**Comment by mcosmin222** [comment]
Sorry, I've been busy with some other things. Hope you are well as well :)

I will test these over the weekend.

**Comment by mcosmin222** [comment]
Am I remembering things or the HEVC extension used to be free for x64 and it is no longer so?
I now seem unable to play videos that were once playable..

**Comment by villagra** [comment]
There is still one free but it's hidden in the store: https://www.microsoft.com/en-us/p/hevc-video-extensions-from-device-manufacturer/9n4wgh0z6vhq

**Comment by mcosmin222** [comment]
Even with that, my big, slow hevc video won't play anymore in anything but VLC. I am pretty sure it used to work for in ffmpeginteropx...

Strange things...

**Comment by villagra** [comment]
I've also seen some big files that don't play correctly... only vlc managed somehow.

**Comment by mcosmin222** [comment]
I think I found a special case file were audio samples come with duration 0.

Sorry, totally unrelated to this.

**Comment by lukasf** [comment]
VLC uses FFmpeg only for the pure decoding part. All format/container parsing is done using custom code in VLC. We use FFmpeg also for format/container parsing, that is a major difference. So it is not a surprise that there are files that do play in VLC but don't play through FFmpegInterop.

@mcosmin222 Can you play that HEVC file with SW decoder?

**Comment by mcosmin222** [comment]
It is unrelated to HEVC, I hooked up the debugger and discovered the issue #196

**Comment by mcosmin222** [comment]
So I think I'll finally be able to try it out this weekend.

**Comment by mcosmin222** [comment]
Well, whatever it is that it was done here, I can't play any video files anymore.
Nothing seems to be wrong, they just don't start playing.

The same files work on the master branch.

@lukasf 
I will upload the file. Can you provide a disposable address to email you the download link?

**Comment by mcosmin222** [comment]
Fixed ^^

**Comment by lukasf** [comment]
Oh, thanks, I only tested the CPP sample :D

**Comment by mcosmin222** [comment]
It never crossed my mind to check the CPP sample ^^

**Comment by lukasf** [comment]
How is the status of this? I think we should get this into the repo. I merged master branch and fixed clean audio. I think we need to add some documentation on this.

Should FastSeek be enabled by default? It currently is, but it can have a minor negative effect on seek behavior, when seeking backward and forward repeatedly. I could fix most of these issues, but in rare cases there is still a negative effect. Also, precision of my fixes is reduced when MediaPlayer.PlaybackSession is not assigned to FFmpegMSS. It still works pretty well without, but having it assigned makes things better. Currently, I'd propose to disable FastSeek by default and add remarks on the session stuff into it's XML comments. Then, when people enable it, they hopefully read those comments and assign the session for best seek behavior.

We could solve the above problems, if we'd provide a seek hint (e.g. mouse or keyboard seek). But I think it's a minor optimization that could be done at a later point, if required. For my taste, the auto behavior is nearly perfect, when session is applied.

@sudongg Am I right in assuming that you are going to use your own implementation anyways? I tried a few things to optimize for that one file you had, by adding an offset to the actual position reported. It had a minor effect, but I don't know if it is what you expected. I don't even know if it was better, it felt a bit different at least. To me it does not make much sense to report wrong timestamps for all files, just to fix one file with a (today) very rare format. I could imagine adding an optional parameter (e.g. FastSeekFrameOffset) if it helps you for your scenario. But maybe you are not following that road anyways.

**Comment by mcosmin222** [comment]
Hi @lukasf,

I will take a look at this, so we can merge it in too.

**Comment by mcosmin222** [comment]
Looks good

**Comment by lukasf** [comment]
I have done some testing. When I enable FastSeek without having the PlaybackSession assigned, seek results are not very good when using keyboard seek (forward/backward switching). So I decided to disable FastSeek by default and added comments on PlaybackSession property. So devs need to enable it manually, and then they will hopefully read the comments and use PlaybackSession.

**Comment by mcosmin222** [comment]
If it's that bad, maybe we should throw an exception when attempting to set fast seek without a session. This will catch their eye.

**Comment by lukasf** [comment]
Thing is, we cannot throw on construction of the instance, since the PlaybackSession can only be assigned later, after playback has started. I'd say, either we leave it as it is now (maybe add some docs in the readme), or we ignore the FastSeek flag when PlaybackSession is not assigned.

**Comment by lukasf** [comment]
@mcosmin222 Can you test GPU device change on this branch, with both FastSeek enabled and disabled?

I do skip FastSeek now, if PlaybackSession is not assigned. And I have added a switch and small hint in the samples. That should be enough I guess.

**Comment by mcosmin222** [comment]
For some unholy reason, it crashes.

The call to av_buffer_unref(&avHardwareContext); at line 1751 releases the pointer,and then it is passed as null to the code further down.

HRESULT hr = D3D11VideoSampleProvider::InitializeHardwareDeviceContext(mss, avHardwareContext, &device, &deviceContext, deviceManager, &deviceHandle);

**Comment by mcosmin222** [comment]
Time for bug hunting I guess.

**Comment by mcosmin222** [comment]
Well, it is not very stable. It is either something that I did or seeking changes seem to have affected the way this works. 

Sometimes video gets "stuck" with a blank screen after switching GPUs.

**Comment by lukasf** [comment]
Oops, I accidentially pushed the fix directly to master branch. I intended to do a PR for that. Can you check if it works with latest master branch changeset? I am sorry, I introduced that bug right before merging. Not a good idea to do last minute fixes to code that I cannot even test... o.O

It's strange though that this does not work on the branch here. Seeking should be same during device change, as far as I see it. It's really too bad that I cannot reproduce it here.

**Comment by mcosmin222** [comment]
I will try it out in the morning.
do you have multiple video outputs? Maybe this can be reproduced with multiple monitor setup.

**Comment by mcosmin222** [comment]
This is the stack trace at which is freezes, it seems to enter an infinite loop.


 	FFmpegInterop.dll!FFmpegInterop::UncompressedSampleProvider::GetFrameFromFFmpegDecoder(AVFrame * * avFrame, __int64 & framePts, __int64 & frameDuration, __int64 & firstPacketPos) Line 107	C++
 	FFmpegInterop.dll!FFmpegInterop::UncompressedSampleProvider::[FFmpegInterop::MediaSampleProvider]::CreateNextSampleBuffer(Windows::Storage::Streams::IBuffer ^ * pBuffer, __int64 & samplePts, __int64 & sampleDuration, Windows::Graphics::DirectX::Direct3D11::IDirect3DSurface ^ * surface) Line 54	C++
 	FFmpegInterop.dll!FFmpegInterop::MediaSampleProvider::GetNextSample() Line 225	C++
>	FFmpegInterop.dll!FFmpegInterop::FFmpegInteropMSS::OnSampleRequested(Windows::Media::Core::MediaStreamSource ^ sender, Windows::Media::Core::MediaStreamSourceSampleRequestedEventArgs ^ args) Line 1739	C++

**Comment by mcosmin222** [comment]
Doing another regular seek seems to be fixing the problem. So it appears the issue is with the way seeking is done when doing device changes.

**Comment by mcosmin222** [comment]
Seems better now.

**Comment by lukasf** [comment]
Nice catch. That should be it.

**Comment by lukasf** [comment]
So... are we all good now with this? Any remarks on the feature or API?

**Comment by mcosmin222** [comment]
I will need to give it some more testing.

**Comment by mcosmin222** [comment]
So for my own use cases this is pretty good. I integrated it with my own app which has this seek forward by 30 seconds / seek back by 15 seconds functionality and it works pretty great with setting the media playback session. HEVC seeking is also noticeably faster. 

With regards to the API itself: I think what's done already is enough to point people in the right direction. Maybe we should put a warning so it becomes visible at compile time as well (i'm not sure if we can set custom warnings with C++ other than deprecated - which is not a good fit for this), but I think at this point it is a bit too much and it works just fine the way it does right now.

**Review by mcosmin222 — APPROVED** [review]

**Comment by lukasf** [comment]
Okay then let's merge this now.

**Pull request merged**
