### PR TITLE
Remove IKeyValuePair interface implementation

### LINKED ISSUE #118: KeyStringValuePair makes .net native toolchain go in infinite loop
This is one of the weirder ones.

In PR #114 , I added a new class called KeyStringValuePair, which inherits from IKeyValuePair<string, string>. Apparently, this interface implementation causes the .net native toolchain to go in infinite loop while compiling a CS project referencing ffmpeginterop. 

This is reproducible with the sample app. If you try to build the CS sample in release mode, you will see it goes on compiling forever. In task manager, net native toolchain will be busy, with roughly 20% CPU usage on my laptop, but it will never end (I let it run over night actually).

When I removed the interface implementation, it compiles almost instantly. This is probably related to how the projection works with .net native. 

I suggest we remove that interface in the official repo as well, otherwise people will not be able to compile their apps anymore. Besides, I don't think it brings much value anyway, the class should behave more like a tuple rather than a KeyValuePair in a dictionary.

### PR DESCRIPTION
**Pull request by mcosmin222**
This should fix #118 
I also uped the target versions for all projects, so they are all in unison as well as targeting the more modern windows 10 versions.

### CODE REVIEW

**Comment by lukasf** [comment]
I found a different solution: The problem seems to only occur when we export a public type with that interface. By making the type internal and exposing only the interface, build works fine. This fix is a breaking change, but since this feature was just added, I don't expect many problems.

**Comment by mcosmin222** [comment]
Well, it cannot be more breaking than the app never compiling ^^. Good idea!
I also just discovered another mistake and fixed it.

**Comment by lukasf** [comment]
That destructor is not even needed, the vector will be auto cleaned up. I already noticed this a while back but forgot to mention. Let's just remove it.

**Comment by lukasf** [comment]
The only places where you actually need a destructor is when you hold unsafe stuff (pointers, handles) or when you need to break reference cycles manually. Everything else, especially all WinRT classes will be auto cleaned up by the runtime, like in C#...

**Comment by mcosmin222** [comment]
I initially did have some unsafe stuff in that class at some point, but then removed it and forgot about the destructor.
I got completely surprised by it too.

**Pull request merged**
