### PR TITLE
Introduce new NuGet package layout for v2.0

### PR DESCRIPTION
**Pull request by lukasf**
Finally I found the time to do the new NuGet Layout!

These are the new packages:
- FFmpegInteropX.Desktop.Lib
- FFmpegInteropX.Desktop.FFmpeg
- FFmpegInteropX.UWP.Lib
- FFmpegInteropX.UWP.FFmpeg
- FFmpegInteropX -> This is the overall package with references either UWP or Desktop Lib+FFmpeg, depending on target

Other changes:
- .Net 8 compatibility, but runs on .net 6 as well (WinUI sample is .net 8, unit tests are .net 6, to show this works)
- Added minimum target version for UWP
- Included Readme.md in nuget packages
- Added build script to create overall package

### CODE REVIEW

**Comment by brabebhin** [comment]
Integrated the ffmpeg desktop build with my app, works nice.

Good work!

**Comment by brabebhin** [comment]
Also works with net 8.

**Review by brabebhin — APPROVED** [review]

**Comment by lukasf** [comment]
@softworkz I also added a way to override the FFmpeg build dependency NuGet name and version (using e.g. a Directory.Build.props file). I thought this might come in handy, if devs want to compile against their own ffmpeg build, possibly with a different NuGet package name and version. Check the last commit.

**Comment by softworkz** [comment]
> @softworkz I also added a way to override the FFmpeg build dependency NuGet name and version (using e.g. a Directory.Build.props file). I thought this might come in handy, if devs want to compile against their own ffmpeg build, possibly with a different NuGet package name and version. Check the last commit.

Thanks a lot for provisioning for that case. 

Thanks again for merging my code contributions. This allowed me to consolidate and get me up to date (previously I had my changes based on an earlier version), so I'm always equal now to the winui branch here - except for the vcxproj and nuget package building.  All nuget packages have a different naming to avoid collisions/ambiguities.
Right now I have a single PS script to call, which builds everything (except ffmpeg) and pushes it to an Azure DevOps package feed, Then I just need to update packages in the consuming projects and the DevOps builds are working fine without needing to take any extra steps.
Given this high level of comfort achieved, I hope you'll understand that I don't want to touch this part again right now... 😉 

But I'm sure it will be useful for others.

**Comment by lukasf** [comment]
> Given this high level of comfort achieved, I hope you'll understand that I don't want to touch this part again right now... 😉

Sure, I fully understand that. Just wanted to mention it.

**Comment by lukasf** [comment]
The last thing missing here is moving the BasicVideoEffect to a separate NuGet package, so we don't have a dependency on Win2d on our UWP main packages. I will try to do that in the next days.

Oh and by the way, should we completely drop ARM (32 bit) support? It's really a dead platform, only used by WindowsPhone back in the days. On the Desktop build, I had to remove it anyways, because WinUI does not support it. Maybe we should drop it on UWP as well.

I even thought a bit about dropping x86 as well. Percentage of 64 bit OS on Windows has gone up from 99.7% to 99.9% last year. But maybe we should still leave that decision to app developers, not force it through our lib (yet). Maybe in a few years we can consider to stop delivering it.

**Comment by brabebhin** [comment]
How about moving the effect to the c++ sample instead?

The effects are broken in winui 3, i don't think it's worth the hustle and the ensuring bug reports. 

I agree with dropping ARM, i don't think there's any devices running the 32 bit version anymore.

**Comment by lukasf** [comment]
ARM builds removed. I left the option in the build scripts, just not using it in the default builds (and not in our NuGet packages). But if someone desperately wants, they can still do an ARM builds using our build scripts.

I agree that removing x86 would be too early. We are not there yet.

About the video effects, I will only make an UWP package (until video effects work in WinUI, which is improbable to happen within the next five years).

**Pull request merged**
