### PR TITLE
Minimum subtitle duration

### PR DESCRIPTION
**Pull request by mcosmin222**

### CODE REVIEW

**Comment by mcosmin222** [comment]
@lukasf 
Nice work!

One question though: Shouldn't we forward the overlap prevention property and the additional subtitle duration to the subtitle parser MSS as well?

**Comment by lukasf** [comment]
Yes you are right, good catch. I pushed a fix.

**Comment by lukasf** [comment]
There is one scenario where the duration editing currently does not work: Subtitles with infinite (negative) cue duration, which get removed when the next subtitle occurs. This is the case with all bitmap based subtitles (BluRay PGS or DVD subs) plus a few rather exotic formats. We had to create this rather complex "reference track" stuff to get this handled properly and flicker free. I think we could get this to work as well, but it will be a bit more difficult. And we probably cannot allow overlap for bitmap based subs, since they target a specific screen area.

Oh and by the way, I set prevent overlap to true as default. Do you think that is a good default? I originally set this to test it quickly, before updating the samples.

**Comment by mcosmin222** [comment]
Yes, having overlap prevention as default is a good idea.

I think the case of infinite length subtitles is a non issue. The use case I see for increasing duration or setting a global minimum duration is when dealing with somewhat broken files or where subs don't match exactly the file (as with subtitle delays). In the case of infinite length subtitles, the subs stay on for until the next shows up anyway, so I think the use case does not apply there.

**Comment by mcosmin222** [comment]
I think this is ready for merge.

**Comment by lukasf** [comment]
I have been working on implementing duration changes for infinite duration subs. It might not be a use case for you, but for me it is. But it might take a while until I finish it, so I will do that as a separate PR. This one seems fine to me.

**Pull request merged**
