### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by brabebhin**
Technically it should work, but there's still an activation factory exception, as I feared, since the .net core doesn't have a package identity. I will need to find some solution to this.

### CODE REVIEW

**Comment by lukasf** [comment]
I got the tests running here! Took me a few hours to get things right. One irritating thing was that MSTests does not find any tests if target platform version is bigger than 17763. Luckily, this is the lowest platform we support. Took me at least one hour to figure this out alone. Then struggle with different dependencies and all. First I thought we need a manifest file and list all classes, but it was not required in the end.

Please let me know if tests run on your side as well. If this proves to be stable, we can start adding some real tests.

**Comment by brabebhin** [comment]
Amazing! This actually works! 

I too spent some time with the manifest fie, then had to do some other unrelated things.
I wonder how long we can go with this.

**Comment by lukasf** [comment]
After updating the MSTest NuGet packages, I could use later framework versions. Switched to 22000 now and all tests still run fine.

I added some more tests. And guess what? Just found the first bug using unit tests!! ^^
FFmpegMediaSource.HasThumbnail always returns true, even when there is no thumbnail stream available. Fixed now.

StorageFile.CreateStreamedFileFromUriAsync does not seem to work. Maybe it requires UWP. Getting FileNotFoundException on OpenRead of the returned StorageFile. Either we need to download the files to temp folder, or we checkin a few (very small) files to the repository. I don't really want to blow up the repo with test data, so only very small files, if any at all.

**Comment by brabebhin** [comment]
I think a bunch of very low resolution, blank files (like slient PCM or a black screen video) can be effective to test some stuff and also not require too much space.

We could use them to test seeking, stream switching and other related functions. We probably can't accuratly test playback accuracy.

**Comment by lukasf** [comment]
Yes. And additionally, we can download a few files in AssemblyInitialize method, so they are downloaded only once and then available for all tests in that session (and cleanup afterwards in AssemblyCleanup). But we should only download files from reliable sources. I see e.g. mplayerhq samples as a reliable source.

**Comment by brabebhin** [comment]
Audio is pretty easy to generate by ourselves using Audacity. For video it is trickier, but again, I think we can use ffmpeg.exe to generate some blank videos as well.

I am not sure about downloading them from a third party, they may become unavailable, we might get ipblocked etc. I think we should first try to compile a a list and see how big it would get.

**Comment by brabebhin** [comment]
I took the liberty to embed a file in the project and see how it goes on. It is a small-ish 500KB file, which shouldn't impact us too hard.
We can probably have a different repo with test files.
I also added some helper methods that I use in my own player to help us with basic MediaPlayer operations.

I also tried to fix your test with the streamed file. I have no idea why it doesn't work. 
For that particular case, we can load that URL in a memory stream using a http client and use the memory stream to create the media source. I am not sure how much memory the appveyor has available for this, that file looks big-ish (7.8 MB or something)

**Comment by lukasf** [comment]
So, tests are finally run in AppVeyor as well. Only problem is that currently the tests use a NuGet package instead of the actual build. Theoretically we could reference the DotNet project (WinRT wrappers) directly. But it does not build in normal configuration because of the bindable attribute in our IDL files. We either need separate build configurations (WinRT and UWP), or we need to remove the bindable attribute.

**Comment by lukasf** [comment]
For playback testing, I have a different idea that does not involve actual MediaPlayer. I don't really want to wait multiple seconds for MediaPlayer to reach a certain position. We could add a class MediaSourceReader that is created with a FFmpegMediaSource as constructor parameter. It will cast the FFmpegMediaSource to our internal implementation. Then we can add methods in FFmpegMediaSource (not in IDL, so they are only visible from MediaSourceReader) to programmatically perform seeks, select streams and read samples. That way, we can test playback scenarios at very high speed and with reliable and reproducible position behavior. It might even be useful for some custom rendering or decoding / transcoding scenarios. The read methods would return MediaStreamSamples, people could extract data from them for whatever reason. It would be a bit like FrameGrabber, but more powerful and flexible (e.g. support D3D), but with a more difficult API.

**Comment by lukasf** [comment]
About the bindable attribute and build configs: I think that separate build configs are inevitable. WinUI will be the dominant platform in the future. Sooner or later we must fully support it. That also means we must use WinUI DispatcherQueue, and maybe other classes at some point. Since we will need separate build configs anyway, we could as well start adding them now. It would help with unit tests and the WinUI sample app (debugging current code without nuget). And we could easily add WinUI DispatcherQueue as well, once we have the separate configs.

Oh and by the way, StorageFile is listed as one of the classes that requires package identity. That's not really true, since it mostly works. But maybe the streamed file stuff is something in there that does not work in unpackaged apps (and unit tests).

**Comment by brabebhin** [comment]
Good idea with the wrapper class. It does open up a few possibilities.
I also agree about winUI. We should start making provisions to have it fully supported. I think MPE was the only missing part that we needed to achieve support for win UI. Once they released the mpe to production builds i will also start migrating my app to winUI. 

Maybe we should use pass-through subtitles after all. I know i said I'd give it a try, but I've been rather busy in the weekends,  and this week continue for another few weeks.

**Comment by lukasf** [comment]
Oh man, WinUI is really such a PITA. It must be one of the worst tech releases MS has put out. I mean, it's not a bad technology by itself. But the way it is integrated into the other MS tools is just beyond bad. It does not interop nicely with any other MS tech. Why the f*** can't I just add a reference to a WinRT project from .NET Core and use the classes? Every other tech interops in any direction without further ado. C++/CX, C# F# VB. But not so WinRT. No no, that would be too easy.

I mean, ok, it does not work out of the box. We need to manually add CsWinRT package. If that was it, ok, I would not complain. But no, that's not it. We have to manually tell CsWinRT which winmd files to process, by manually editing stuff into the project file. Why the *** does it not just process all referenced winmd files??? Holy cow. But is that all? No of course it is not all. We even need to manually copy the native dll into the right subfolder (not project output folder, but runtimes\win10-x64\native). Otherwise, the dll is not found and we get the activation factory error. And if you want to do this for an app, you need additional tricks to make MSBuild accept the copied file as true project output and deploy it. MS guides tell us to create NuGet packages, but having NuGet packages inside a project makes debugging and development loop a pain. If you want to do without NuGet, you have to find out the required steps yourself (and it is a lot of steps, through a minefield of problems and bugs).

Well, but after all, UnitTests and WinUI Sample app now work with direct project references, so we can edit, build and debug without the need to create NuGets inbetween. I just wished this would have been WAAAAAAAY easier...

**Comment by brabebhin** [comment]
Nice work. So that's where the activation factory came from. It never crossed my mind lol. 

I think the problem comes from the way dotNET is handled now. They decided to scrap all native interops, like winRT and the like to not "favor" windows over other platforms. Then the cswinrt thingy came along and from what I've read, it's performance is abhorrent.

I'm seriously considering rewriting my whole app in c++/winRT to avoid these c#/dotNET shenanigans. It's great for web and i use it at work for that, but now the client side is fubar if you try anything other than a demo weather app.

**Comment by lukasf** [comment]
I fully understand that they pulled out the WinRT compat thing into its own NuGet package. But then I'd expect it to work like this: I add the CsWinRT nuget, I add a package reference to my WinRT component, and then things JUST WORK. But no, they don't work at all. So many additional manual steps involved (and poorly documented), so many pitfalls. I mean really, I can't be too hard to just auto generate wrappers for all referenced WinRT components, without manually editing project files. It's ok to allow customization via project files. But as default, things should just work. And it also can't be too hard to put the assemblys in the right place, where they are picked up by .NET Core. I mean, how difficult is that. I managed with a few lines of MSBuild. It could have been done automatically by CsWinRT, it knows where the assemblys must be places. But no...

C++/WinRT also can't generate XML docs from code comments. Something so basic. It is the way how probably 99% of API docs are created. It works in every language Microsoft has developed. But it does not work in their new, most recommended language? Come on Microsoft, you can't be serious. Are you too poor to hire one developer, to just make basic WinRT scenarios work without pain and headaches? I really don't get it.

To me, this does not even look half way finished. And still it's their shiny new, officially recommended tech, dropping support for C++/CX (which works way easier and interops nicely with all other techs).

One of the biggest performance issues is that they still don't have native AOT compilation in .NET Core. This is a real performance killer, especially for .NET <-> native interop. I still remember how much UWP performance was boosted when they introduced .NET Native. We really need that for using WinUI with .NET Core. All the interop that happens during data binding from native UI to .NET classes could be massively accelerated by native compilation.

**Comment by brabebhin** [comment]
Perhaps we should consider contributing this to the cs/winRT project?
Yeah, the nativeAOT is another pain point I have been following with the .net project. That got delayed several times. Not sure why they can't just resume .net native. Oh well...

**Comment by lukasf** [comment]
True. I have created a first PR on CsWinRT, to make it auto generate all projections without manual project file patching. Let's see how they like it.

**Comment by brabebhin** [comment]
The only way I can see them not liking it is it it somehow generates conflicts with prepackaged cs/winrt components (which I think it is the entire Windows namespace).

**Comment by lukasf** [comment]
Huh, finally got this working again including CI build. Are we good to go with this one?
It is a good base to start with, I think. We can add more/better tests any time.

**Comment by brabebhin** [comment]
Yeah, I think we're good to go.
I don't think your PR on the cswinrt project is going to get merged any time soon either.

**Pull request merged**
