### PR TITLE
Fix metadata encoding

### PR DESCRIPTION
**Pull request by lukasf**
This should fix the encoding of metadata tags for #120

### CODE REVIEW

**Comment by lukasf** [comment]
The only thing I am not sure about: Should we read keys as UTF8 as well? Usually tag keys are always ASCII, so I think that UTF8 is not needed there (and I assume that most formats do not support more than ASCII for keys, but that is just me guessing).

**Comment by mcosmin222** [comment]
Isn't utf8 backwards compatible with ascii? Afaik, ascii characters in utf8 keep same bytes. I think utf8 would be the more incompasing encoding.

**Comment by lukasf** [comment]
I think we should also encode parameters passed to ffmpeg as Utf8 (see latest changeset). Usually these will all be ASCII, but while we are at it, I'd clean this up as well.

**Comment by mcosmin222** [comment]
Looks good!

**Comment by lukasf** [comment]
Merged.

**Pull request merged**
