### PR TITLE
Add support for inline subtitle effects

### PR DESCRIPTION
**Pull request by lukasf**
This adds parsing of inline subtitle effects. I added a CopyStyle() function to prevent the problems @pashmak73 had on his first attempt. For me this works well.

Some notes on positioning: I also added a CopyRegion() function to allow position overrides, but it is not used right now. Positioning is a bit difficult: The position must be interpreted differently for each of the 9 alignment options, so for top left alignment this is the top left corner, for bottom right alignment it is the bottom right corner, etc. Additionally, using the normal Position and Extent properties of the TimedTextRegion did not work properly for me when I implemented text subtitles back then. That is why I do the positioning using the "Padding" property. Position/Extent are set to fill the complete screen, the padding then moves the sub into the right position.

### CODE REVIEW

**Comment by pashmak73** [comment]
Keep in mind, code is only do effect to all of line!
A line can be very different.
For example:
See this: 
`Dialogue: 0,0:00:04.10,0:00:26.10,HaneMain,,0,0,0,,enable{\b1} bold{\b0} and{\i1} italic `

This is a line which should show like this:
image

`ENABLE BOLD` is `bold`, `AND` is `normal`, `ITALIC` is `italic`.
Multiple effects are supported in lines, even enabling and disabling italic, bold, underline and etc.

For position it is very difficult than you think.
Just look at this subtitle:
image
```
Dialogue: 0,0:03:15.19,0:03:23.09,Sign : Loud,Sign,0,0,0,,{\pos(496.667,535.333)}پر سر و صدا
Dialogue: 0,0:03:16.11,0:03:23.09,Sign : Short,Sign,0,0,0,,{\pos(1663.333,701.333)}کوتاه
Dialogue: 0,0:03:17.36,0:03:23.09,Sign : Calm Down,Sign,0,0,0,,{\pos(1639.334,275.334)}نفرت انگیز
Dialogue: 0,0:03:18.86,0:03:23.09,Sign : Immature,Sign,0,0,0,,{\pos(536,842.667)}نا بالغ
Dialogue: 0,0:03:20.58,0:03:23.09,Main,Yuno,0,0,0,,به طور کل ، برای زنا اصلا جذاب نیستی
```
Rotation?!
image
```
Dialogue: 0,0:02:49.35,0:02:52.31,Prodigy,sign,0,0,0,,{\frz339.4\pos(1120.333,221.333)}اعجوبه دست نشانده ملکه بالاخره به تاج می رسد ‏‏‏!‏‏‏
Dialogue: 0,0:02:49.35,0:02:52.31,Distant,sign,0,0,0,,{\frz348.4\pos(1211,278)}در مملکت غریب
```
Even win api doesn't support rotation:
image

**Comment by mcosmin222** [comment]
Nice work guys.

Alas, on the other hand, i don't think winRT can support combinations of styles on different words like that. For that we will have to implement our own engine, which is quite a lot of work...

Remember we are limited by winRT quite a lot.

**Comment by pashmak73** [comment]
@mcosmin222 You are wrong. Here this is from MediaPlayerCS example:
image
`Dialogue: 0,0:00:04.10,0:00:26.10,HaneMain,,0,0,0,,enable{\b1} bold{\b0} and{\i1} italic {\i0\u1} underline`

**Comment by lukasf** [comment]
I am aware that that is only a partial solution. It was not my plan to do a complete re-implementation of the SSA API. That would involve lots and lots of work, and even animations and stuff which will never be possible through Windows APIs. If we'd want 100% support of all SSA stuff, we'd have to include libssa and render the subs through that. But it's not only quite some work, but it would probably also put quite a performance penalty on the app. I'd prefer the current light-weight approach with support for the most important features.

At first I was surprised that per-word formatting works when loading a sub through Windows APIs. But now I see that TimedTextLine has a property Subformats, each Subformat has a start index, length and a style. So instead of changing the complete style of a cue, we could use Subformats to change only specific parts of it.

@pashmak73 I have invited you as collaborator, just in case. Feel free to work directly on this branch if you like to improve something. I will take a closer look at this subformats thing, maybe we can get that working.

**Comment by pashmak73** [comment]
@lukasf please send your invitation to my real account @ramtinak .

**Comment by lukasf** [comment]
Done

**Comment by lukasf** [comment]
That was surprisingly easy. Check last commit for per-word styling support! ;)

Feel free to add in font size, font name, colors, whatever you think makes sense!

**Comment by mcosmin222** [comment]
Ok. I stand corrected then. One of the moments i am pleased to ne wrong :)

**Comment by ramtinak** [comment]
Tested SSA sub item:
`Dialogue: 0,0:00:04.10,0:00:26.10,HaneMain,AAAA,0,0,0,,enable{\b1} bold{\b0} and{\i1} italic {\i0\u1} underline`

I don't know why but I'm getting an exception with below code ( if I use `originalStr = originalStr.substr(firstCm+1, endCm - firstCm +1);`)
somehow, it will throws an 'Value does not fall within the expected range` exception.
here is my code:
```c++
auto str = utf8_to_wstring(std::string(subtitle.rects[0]->ass));
auto originalStr = str;
int commaIndex = 1;
while (true)
{
	auto firstCm = originalStr.find(',');
	if (firstCm != originalStr.npos)
	{
		//Format: Layer, Start, End, Style
		// third comma
		if (commaIndex == 3)
		{
			auto endCm = originalStr.find(',', firstCm );
			if (endCm != originalStr.npos)
			{
				//below code is working but shows : HaneMain,AAAA,0,0,0,,enable{\b1} bold{\b0} and{\i1} italic {\i0\u1} underline
				originalStr = originalStr.substr(firstCm+1);
				// below code will throws an exception: Value does not fall within the expected range
				// originalStr = originalStr.substr(firstCm+1, endCm - firstCm +1);
				// printing 
			}
			break;
		}
		else // skip backward words
			originalStr = originalStr.substr(firstCm+1);
		if (commaIndex > 4)
			break;
		commaIndex++;
	}
	else
	{
		break;
	}
}
```
It is very weird, because when I use only `originalStr = originalStr.substr(firstCm+1);` I can see 'HaneMain,AAAA,0,0,0,,enable{\b1} bold{\b0} and{\i1} italic {\i0\u1} underline`
but when I add `, endCm - firstCm +1` or `, endCm` or `, 1` it will throws `expected range` exception again.

I've added these code after `while loop`:
```c++
auto cmm = originalStr.find(',');
if (cmm != originalStr.npos)
{
	originalStr = originalStr.substr(0 , 3);// just for test I put 3, but throws that exception too even If I use cmm too
	originalStr = originalStr.append(L" ???????????? EXISTS   |  ");
}
else
	originalStr = originalStr.append(L" ???????????? Doesn't EXISTS");
```
but this will throws that exception too:|

**Comment by ramtinak** [comment]
I found something else, it seems `ReadStylesV4Plus` is not working at all. because always size() returns 1 and using this: `style = styles.begin()->second;` will throws this:
image

**Comment by lukasf** [comment]
I think that this could be the problem:

			auto endCm = originalStr.find(',', firstCm );

It should be 

			auto endCm = originalStr.find(',', firstCm + 1 );

Otherwise, endCm == firstCm.

But then, I am not really sure what you are trying to accomplish. We do already read the style name here:

				int startStyle = -1;
				int endStyle = -1;
				int lastComma = -1;
				bool hasError = false;
				for (int i = 0; i < textIndex; i++)
				{
					auto nextComma = str.find(',', lastComma + 1);
					if (nextComma != str.npos)
					{
						if (i == styleIndex)
						{
							startStyle = (int)nextComma + 1;
						}
						else if (i == styleIndex + 1)
						{
							endStyle = (int)nextComma;
						}
						lastComma = (int)nextComma;
					}
					else
					{
						// this should not happen. still we try to be graceful. let's use what we found.
						hasError = true;
						break;
					}
                                 }

This does already work and the style (including fonts, etc) is used.

What I ment with "add font size, colors" is to add support for overrides in style effect, such as {\fs14} to change FontSize to 14, {\fnArial} to set font, {c1H&xxxxxx&} to set color. Here you can find a list of all inline effect tags:

http://docs.aegisub.org/3.2/ASS_Tags/

About your last issue, I don't even find `styles.begin()`. If you have an original SSA file that does not work with _unmodified_ FFmpegInterop, please upload it so we can take a look.

**Comment by ramtinak** [comment]
First I thought problem is that style name don't get correctly, thats why I wrote above codes!
Also it seems your code isn't working properly too:
```SsaStyleDefinition^ style = nullptr;
auto styleNNNN = convertFromString(str);
if (!hasError && startStyle > 0 && endStyle > 0)
{
	auto styleName = convertFromString(str.substr(startStyle, endStyle - startStyle));
	styleNNNN = styleName; // throws `Value does not fall within the expected range` exception
	if (styles.find(styleName) != styles.end())
	{
		style = styles[styleName];
	}
}
```

Now I believe something is wrong with `ReadStylesV4Plus`. because always `styles` returning 1 item, if you use that item it will throws this exception:
image

Here this is my sub: [sub.zip](https://github.com/ffmpeginteropx/FFmpegInteropX/files/2926404/sub.zip)
(has 22 styles)
Here, this is from external sub using ffmpeg:
image
and external sub using winapi:
image
-
I know what you said about font name, color and etc. I'm gonna add it.

**Comment by lukasf** [comment]
Thank you. The file looks fine at first sight. I will test it when I am back home.

**Comment by ramtinak** [comment]
Supporting font family and font size added.
Supporting font color is much different since ssa subtitle uses "BGR" (`&H<bb><gg><rr>&`), I tried some codes but every time I get black color.
Tested color: `&HDD19C9&` color: `purple`

@lukasf Can you take a look at it later?

**Comment by mcosmin222** [comment]
@ramtinak, I see you created your own parser for dealing with Colors. Have you tried using this method instead?

https://docs.microsoft.com/en-us/uwp/api/windows.ui.colorhelper.fromargb 

It should be pretty easy to inject it in your current FixColor method. You just need to convert to byte the existing substrings. Most likely that reinterpret cast fails. Int is signed, the reinterpret cast will likely generate the wrong A value.

**Comment by lukasf** [comment]
Cool, good work @ramtinak!

For the colors: You need parse them as hex (base=16)!

            int convertHexToInt(Platform::String^ str)
		{
			const wchar_t* begin = str->Data();
			return std::wcstol(begin, nullptr, 16);
		}

Then you need to shift and add alpha channel:

    ColorFromArgb(color << 8 | 0x000000FF);

FixColor() method should not be needed, RGB order is supposed to be what UWP expects.

I have been looking at the file you sent. There are two issues. I could fix the first, but the second is more complicated. Somehow the parameter parsing with sscanf does not work properly. I will keep digging...

**Comment by ramtinak** [comment]
image
Font color & border color support. it seems good to me.

**Comment by lukasf** [comment]
I have fixed the problems with the subtitle file you provided. We used a wrong string to identify V4.00+ files (ASS format). Additionally, I assumed that all values in the style definition are int. But it looks like some of them can be float as well. Both issues are fixed and the file plays well now.

I have also noticed that our outlines are too thin, when comparing with other players. Now I multiply with 2, which is much closer to the expected output.

**Comment by ramtinak** [comment]
Looks good that these issues is fixed, but I encountered to another issue!
text line:
`Dialogue: 0,0:00:02.10,0:00:26.10,HaneMain,AAAA,0,0,0,,enable{\b1} bold{\fnViner Hand ITC\b0} and{\fs60\i1} italic {\i0\u1\fnVladimir Script\fs115\c&HDD19C9&\3c&HEEFF00&} underline`
image
it seems changing font color and outline (border) color is not working properly anymore. (I don't know how, but it seems for last word `"underline"` is working well)

**Comment by lukasf** [comment]
The line you pasted only has colors set for the last word.

**Comment by ramtinak** [comment]
Ops you are right, I didn't check for colors.

**Comment by ramtinak** [comment]
And something is really interesting is this:
image

two cue at the correct position(somehow, it should be right not left)!
But when next cue is called, position will change it to current cue:
image

I think now we can support position effect too, since styles issues is fixed.

**Comment by lukasf** [comment]
I have done some optimizations to your code. The methods to parse numbers will automatically read until next non-digital character. So you do not need to subtring before using them. Done some other cleanup as well.

From my testing things work as expected, but please test with your files as well.

Positioning is tricky. Also UWP will sometimes move subs to make space for other subs (if more than one are displayed at the same time). Currently I would not want to touch that area, but you can try if you like.

**Comment by ramtinak** [comment]
OK I will check it tomorrow,
I checked something else, it seems winapi shows correct position for multiple cues which has same time and duration.
image

I will some digging tomorrow for this. I let you know If I find anything good.

**Comment by lukasf** [comment]
Oh by the way, I have an old branch where I tried to add support for embedded subtitle fonts. Some video files have font files embedded, that are supposed to be used by the subs (if the font is not installed). I never finished that work. Maybe now is a good time to dig this up and see if we can make it work.

**Comment by ramtinak** [comment]
I think we should parse font size as double: ( for supporting size like this `\fs10.5` )
https://github.com/ffmpeginteropx/FFmpegInteropX/blob/7de6cc246e291b0011b09bb81f19025ec9cfc584/FFmpegInterop/SubtitleProviderSsaAss.h#L204-L208

**Comment by lukasf** [comment]
Agreed. I can do this when I am home.

**Comment by lukasf** [comment]
You need to use std::stof or std::stod, otherwise you only get the integer part.

**Comment by ramtinak** [comment]
image
I've added line alignment effect support (`\a` and `\an`). also fixes some issue that I mentioned before.

**Comment by lukasf** [comment]
Nice!

**Comment by lukasf** [comment]
So, I pushed my AttachedFileHelper stuff. This should theoretically allow us to extract embedded fonts to a temp folder and hopefully be able to show them. According to what I have read, FontName should be set to something like "ms-appdata:///temp/FFmpegAttachmentCache/MyFont.ttf#MyFont". First the path to the font file, then "#", then the name of the font. 

As I said, it is work in progress, I never actually tested it. I don't even have a file with embedded fonts at hand right now, need to search one in my library.

**Comment by lukasf** [comment]
Well, what I verified is that attached files would be listed in the AttachedFileHelper, with name and mime type. But I never came to test the extraction and font stuff. Instead I worked on other stuff and almost forgot about it. Only now I remembered I still have this. :)

**Comment by lukasf** [comment]
I could get embedded fonts working!! Still not finished, need to clean up cache folder on file close...

I tested with this file, it contains lots of fonts. Looks fine so far.

https://samples.mplayerhq.hu/Matroska/subtitles/embedded_ass/

**Comment by lukasf** [comment]
Yesterday I had a major breakthrough for subtitle positioning: I also saw that when there are multiple subs at the same time, they woul all seem to stick together, even if they have different alignment set. The sample I posted above uses fonts correctly, but due to positioning bugs, it looked horrible.

After lots of testing different stuff, I finally found out what helps: The regions must have different names! If they have same name, even if they are different region instances with different position and alignment, UWP will somehow stick them all together with unpredictable results. With separate names, they all appear at their intended position. I still need to cleanup stuff, but this should finally allow multiple subs at the same time with independent positioning.

The funny thing is: If you set a (non-empty) name on a style, it will crash UWP. That is why I did not set any names. Only now I find out it is needed for region. So region must have name, but style must not have name. 

This subtitle API is really the worst UWP API I have seen until now ;) So buggy, no useful docs, no explanations...

**Comment by mcosmin222** [comment]
Nice work!

I can agree on subtitles API being the worst. Probably because nobody did what we are doing, so docs are mostly for internal usage.

I wonder what we need to sacrifice to get the sacred codex of media APIs from MS.

**Comment by lukasf** [comment]
This is a first version where cue position effects work! Still some work to be done, but for some files it already works!

**Comment by ramtinak** [comment]
I had a chance to test new commits today, It seems good for some subtitles:
OK:
image
```
Dialogue: 0,0:02:49.35,0:02:52.31,Prodigy,sign,0,0,0,,{\frz339.4\pos(1120.333,221.333)}اعجوبۀ دست نشاندۀ ملکه بالاخره به تاج می رسد ‏‏‏!‏‏‏
Dialogue: 0,0:02:49.35,0:02:52.31,Distant,sign,0,0,0,,{\frz348.4\pos(1211,278)}در مملکت غریب
```
Subtitle: [Hanebado! - 01.zip](https://github.com/ffmpeginteropx/FFmpegInteropX/files/2948344/Hanebado.-.01.zip)


but It has issue:
image
```
Dialogue: 0,0:03:15.19,0:03:23.09,Sign : Loud,Sign,0,0,0,,{\pos(496.667,535.333)}پر سر و صدا
Dialogue: 0,0:03:16.11,0:03:23.09,Sign : Short,Sign,0,0,0,,{\pos(1663.333,701.333)}کوتاه
Dialogue: 0,0:03:17.36,0:03:23.09,Sign : Calm Down,Sign,0,0,0,,{\pos(1639.334,275.334)}نفرت انگیز
Dialogue: 0,0:03:18.86,0:03:23.09,Sign : Immature,Sign,0,0,0,,{\pos(536,842.667)}نا بالغ
Dialogue: 0,0:03:20.58,0:03:23.09,Main,Yuno,0,0,0,,به طور کل ، برای زنا اصلا جذاب نیستی
```
It should looks like this one:
image

Subtitle: [Black_Clover_S01E01.zip](https://github.com/ffmpeginteropx/FFmpegInteropX/files/2948343/Black_Clover_S01E01.zip)

**Comment by ramtinak** [comment]
I also find something in my PC (I don't know when/where I downloaded it)
[ass-specs.zip](https://github.com/ffmpeginteropx/FFmpegInteropX/files/2948355/ass-specs.zip)

20 pages all about SSA/ASS subtitle script specs.

**Comment by ramtinak** [comment]
Everything looks great:
image
image
image

**Comment by lukasf** [comment]
Yes! Thinks work pretty solid for me too now. 

I only see a few issues with "normal" positioning now. For some subs, they do not have the offset that is specified in the style. Like in your Black Clover file, the normal subs should have a ~5% offset from bottom (MarginV), but they are rendered exactly at the bottom. The offset is parsed and assigned correctly, so I am not sure why it is not rendered as expected...

**Comment by ramtinak** [comment]
I think I fixed it:
image

**Comment by ramtinak** [comment]
Also I think outline is too thin now(removing  * 2 is not good for readability)
First I multiply it with 1.3 and it was thin, but it seems multiplying it with 1.4 is good: 
image
image

**Comment by lukasf** [comment]
Outline behavior is anyways a bit weird with SSA. Outline thickness depends on the video resolution by default. So if the same SSA file is used on a movie with higher resolution, outline will become thinner. Only if a specific tag is set in the header (ScaledBorderAndShadow: yes), outline is supposed to be scaled up to resolution. Some libs such as libssa will enable scaling by default, if it is not specified, others disable it by default (e.g. VSFilter). We currently always scale it, which is not exactly correct.

Personally, I prefer thin outlines. I will probably introduce a way to override outline behavior (maybe in a separate PR).

**Comment by lukasf** [comment]
I found some ASS files which have vector drawings encoded into text. This needs to be removed.

I think by now we might be more or less feature complete (from the features that are possible at all with UWP APIs).

**Comment by mcosmin222** [comment]
Good work guys. I shall give it some tests and then we can merge, if you think it is ready.

**Comment by lukasf** [comment]
It would be great if one of you guys could also do a (rough) review of the changes. I know it is a lot, but then even more, a second review would be nice. I done a review already, but I cannot approve my own PR.

The one thing still missing from my side is cleanup of extracted font files. Besides that, maybe after a bit more testing, we are fine to merge from my side.

**Comment by ramtinak** [comment]
So I've tested a few subtitles, and I was gonna say everything is fine, that the issues came up!
So I have an 720p x265 video which has one internal (ssa) subtitle. 
I've turn on subtitling for this subtitle and when I hit subtitle OFF, this exception thrown:
image

Also adding two and more subtitles will thrown an exception: (this will happening if you change one default subtitle to another)
image

I've tested with different files and still has these issue.

**Comment by lukasf** [comment]
Thanks! One was actually a bug in the other sync subtitle PR that went unnoticed. The other I just introduced with my last changeset. During refactoring I lost the code to create the unique name for my temp font folder.

Please test these scenarios again with the latest changesets.

**Comment by ramtinak** [comment]
Everything works fine.
Thanks for quick fix!

**Comment by mcosmin222** [comment]
@lukasf, do I merge this?

**Comment by mcosmin222** [comment]
I merged master again into this. Should be ready for the big button. Just tell me if I need to do the merge myself (in case you cannot merge your own branch @lukasf ).

**Comment by lukasf** [comment]
I was a bit busy, merged now. Feel free to push the button next time.

**Pull request merged**
