### PR TITLE
Add HDR check for Xbox

### PR DESCRIPTION
**Pull request by softworkz**

### CODE REVIEW

**Comment by softworkz** [comment]
The HDR check was non-functional on Xbox, which caused crashes when playing HDR videos without HDR being enabled on the xbox.

**Review by lukasf — APPROVED** [review]
Looks good. I added a PlatformInfo class, to prevent unneccessary API calls on PC platform.

**Comment by softworkz** [comment]
> Looks good. I added a PlatformInfo class, to prevent unneccessary API calls on PC platform.

I don't think there's any penalty involved in calling the non-applicable APIs. I'm extensively using them in the app code for automatic refresh rate and HDR mode switching. 
Anyway, the platform check will surely be useful for other xbox-specific tweaks where the situation is different.

Thanks.

**Review by brabebhin — APPROVED** [review]

**Comment by lukasf** [comment]
Meged. Thank you @softworkz

**Pull request merged**
