### PR TITLE
Fix nuget package build

### PR DESCRIPTION
**Pull request by softworkz**
Fix nuget package building which has been broken by this commit:  https://github.com/ffmpeginteropx/FFmpegInteropX/commit/32e9b4c0594ad2c499ac23b248cffe6049e007e2

### CODE REVIEW

**Comment by lukasf** [comment]
Thank you @softworkz. The nuget build is indeed broken. But we don't have a true WinUI build yet, so we cannot use those assemblies. I am working on that in #364. The nuget will look different (probably even multiple nugets), so I am closing this one.

**Comment by softworkz** [comment]
> Thank you @softworkz. The nuget build is indeed broken. But we don't have a true WinUI build yet, so we cannot use those assemblies. I am working on that in #364. The nuget will look different (probably even multiple nugets), so I am closing this one.

Well, I fixed the nugets to work again for UWP and I'm using them for UWP only.

**Comment by lukasf** [comment]
It works, but it is kind of a hack, since you are actually using binaries from "Release_WinUI" build config, which is intended for building the WinUI adapter dlls only, instead of "Release",which is supposed the normal UWP build. This actually has some downsides such as data binding to our classes in C++/CX will be broken.

I will fix the package generation in the other PR.

**Comment by softworkz** [comment]
Yea, it was a bit confusing what your intentions are, because you had added project configurations to the C++ project (like Release_WinUI) but in the nuspec file, you had changed to take the FFmpegInteropX.DotNet.dll from a Release_WinUI output folder even though it doesn't have one. 
So I thought your intention was to build the c++ project as Release_WinUI. 

> I will fix the package generation in the other PR. You can of course use your branch to build private packages, until the official nuget build works again...

Okay, great, we have private packages anyway due to a custom ffmpeg.

BTW, thanks for (both of) your work on this project!

**Comment by lukasf** [comment]
I just found out that it is quite easy to use custom ffmpeg dlls even, with the official nuget package (which includes dependency to FFmpegUWP). The app project just needs to add a manual reference to FFmpegUWP and then set ExcludeAssets=all.

```
    <PackageReference Include="FFmpegInteropX.FFmpegUWP">
      <Version>5.*</Version>
	  <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
```

It is a bit counter-intuitive to add a reference for something you don't want to use. But it does work and allows you to use the official FFmpegInteropX NuGet instead of custom ones.

**Comment by softworkz** [comment]
Thanks a lot for following up. We can't plop in our regular custom ffmpeg binaries because they are built with GCC (much faster than MSVC), not built for UWP and include tons of things which aren't needed for this use case, so  we will need to build them separately using "your" build recipe. Anyway that's the best and safest way to ensure consistency and stability.

Yet, it would still be possible to just build a custom nuget package (with a custom name) for the ffmpeg dlls and use it in the way you describe.
Another way would be to build the ffmpeg package with the same name and the same .nuspec, but a higher version (e.g. 10.x.x). Then you can simply add this package (explicitly) and it will automatically replace the original ffmpeg package dependency of the main nuget package.

**Comment by softworkz** [comment]
I renamed both packages though, because sooner or later, we'll have to do a modification which you might not agree with or can't get merged as early as needed, and then we would run into name/version conflicts for the (main) package.

**Comment by lukasf** [comment]
Okay, that sounds reasonable.

**Pull request closed without merging**
